/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 074f3822-cf16-4774-81fa-559165238f1c

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We define the `SubmodularProblem` structure which encapsulates a finite set `I` and a set function `U : 2^I → ℝ` satisfying monotonicity, submodularity, and `U(∅) = 0`. We define `IsGreedySequenceUpTo` to represent the sequence of sets constructed by the greedy algorithm up to step `K`. We also define `IsOptimal` to characterize the optimal set `S*` of size at most `K`.

The main theorem, `Nemhauser_Wolsey_Fisher_Corrected`, proves that for any submodular problem `P`, if `S` is a greedy sequence of length `K` and `S_opt` is an optimal set of size at most `K`, then `P.U (S K) ≥ (1 - 1/e) * P.U S_opt`. This is the celebrated result by Nemhauser, Wolsey, and Fisher (1978).

The proof proceeds by establishing a recurrence relation for the gap between the optimal value and the greedy value: `U(S_opt) - U(S_{k+1}) ≤ (1 - 1/K) * (U(S_opt) - U(S_k))`. Solving this recurrence yields the bound `U(S_opt) - U(S_K) ≤ (1 - 1/K)^K * U(S_opt)`. Finally, using the inequality `(1 - 1/K)^K ≤ 1/e`, we derive the approximation guarantee.
-/

import Lipo.Prelude

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Definitions of submodularity, monotonicity, and the problem structure.
-/
open Finset BigOperators

variable {α : Type*} [DecidableEq α]

def IsSubmodular (U : Finset α → ℝ) : Prop :=
  ∀ (A B : Finset α) (x : α), A ⊆ B → x ∉ B → U (insert x A) - U A ≥ U (insert x B) - U B

def IsMonotone (U : Finset α → ℝ) : Prop :=
  ∀ (A B : Finset α), A ⊆ B → U A ≤ U B

structure SubmodularProblem (α : Type*) [DecidableEq α] where
  I : Finset α
  U : Finset α → ℝ
  U_nonneg : ∀ S, 0 ≤ U S
  U_mono : IsMonotone U
  U_submod : IsSubmodular U
  U_empty : U ∅ = 0

/-
The Nemhauser-Wolsey-Fisher theorem states that for a non-negative monotone submodular function U, the greedy algorithm achieves an approximation ratio of (1 - 1/e). Specifically, if S_greedy is the set selected by the greedy algorithm after K steps and S* is the optimal set of size at most K, then U(S_greedy) ≥ (1 - 1/e) * U(S*).
-/
variable {α : Type*} [DecidableEq α]

def MarginalGain (U : Finset α → ℝ) (S : Finset α) (x : α) : ℝ :=
  U (insert x S) - U S

def IsGreedyStep (P : SubmodularProblem α) (S_prev S_next : Finset α) : Prop :=
  ∃ x ∈ P.I \ S_prev,
    S_next = insert x S_prev ∧
    ∀ y ∈ P.I \ S_prev, MarginalGain P.U S_prev y ≤ MarginalGain P.U S_prev x

def IsGreedySequence (P : SubmodularProblem α) (S : ℕ → Finset α) : Prop :=
  S 0 = ∅ ∧ ∀ k, IsGreedyStep P (S k) (S (k + 1))

def IsOptimal (P : SubmodularProblem α) (K : ℕ) (S_opt : Finset α) : Prop :=
  S_opt ⊆ P.I ∧ S_opt.card ≤ K ∧ ∀ S, S ⊆ P.I → S.card ≤ K → P.U S ≤ P.U S_opt

theorem Nemhauser_Wolsey_Fisher (P : SubmodularProblem α) (K : ℕ) (_hK : K ≤ P.I.card)
    (S : ℕ → Finset α) (h_greedy : IsGreedySequence P S)
    (S_opt : Finset α) (_h_opt : IsOptimal P K S_opt) :
    P.U (S K) ≥ (1 - 1 / Real.exp 1) * P.U S_opt := by
  by_contra h_contra;
  unfold IsGreedySequence at h_greedy;
  -- By definition of $S$, we know that $|S k| = k$ for all $k$.
  have h_card : ∀ k, (S k).card = k := by
    intro k; induction' k with k ih <;> simp_all +decide ;
    cases h_greedy.2 k ; aesop;
  have h_card_le : ∀ k, (S k).card ≤ P.I.card := by
    intro k
    have h_subset : ∀ k, S k ⊆ P.I := by
      intro k
      induction' k with k ih;
      · simp +decide [ h_greedy.1 ];
      · obtain ⟨ x, hx₁, hx₂, hx₃ ⟩ := h_greedy.2 k; simp_all +decide [ Finset.subset_iff ] ;
    exact Finset.card_le_card ( h_subset k );
  exact absurd ( h_card_le ( P.I.card + 1 ) ) ( by simp +decide [ h_card ] )

/-
For a submodular function U, U(A ∪ B) ≤ U(A) + ∑_{x ∈ B \ A} (U(A ∪ {x}) - U(A)).
-/
lemma submodular_upper_bound (P : SubmodularProblem α) (A B : Finset α) :
    P.U (A ∪ B) ≤ P.U A + ∑ x ∈ B \ A, MarginalGain P.U A x := by
  -- Let $B \setminus A = � \�{x_1, \dots, x_m\}$. We can write $U(A \cup B) - U(A)$ as a telescoping sum.
  have h_telescope : ∀ S : Finset α, P.U (A ∪ S) - P.U A ≤ ∑ x ∈ S, (P.U (insert x A) - P.U A) := by
    intro S; induction' S using Finset.induction_on with x S hxS ih; simp +decide at *; (
    -- By submodularity, we have $U(A \cup S \cup \{x\}) - U(A \cup S) \leq U(\{x\} \cup A) - U(A)$.
    have h_submod : P.U (insert x (A ∪ S)) - P.U (A ∪ S) ≤ P.U (insert x A) - P.U A := by
      -- By the submodularity of $U$, we have $U(A \cup S \cup \{x\}) - U(A \cup S) \leq U(\{x\} \cup A) - U(A)$.
      have h_submod : ∀ (A B : Finset α) (x : α), A ⊆ B → x ∉ B → P.U (insert x B) - P.U B ≤ P.U (insert x A) - P.U A := by
        exact fun A B x hAB hx => by linarith [ P.U_submod A B x hAB hx ] ;
      by_cases hx : x ∈ A <;> aesop;
    simp_all +decide [ Finset.sum_insert hxS ];
    linarith);
  convert sub_le_iff_le_add.mp ( h_telescope ( B \ A ) ) using 1;
  · rw [ Finset.union_sdiff_self_eq_union ];
  · exact add_comm _ _

/-
The gap to optimality decreases by a factor of (1 - 1/K) at each greedy step.
-/
def IsGreedySequenceUpTo (P : SubmodularProblem α) (K : ℕ) (S : ℕ → Finset α) : Prop :=
  S 0 = ∅ ∧ ∀ k < K, IsGreedyStep P (S k) (S (k + 1))

lemma greedy_recurrence (P : SubmodularProblem α) (K : ℕ) (hK : 0 < K)
    (S : ℕ → Finset α) (h_greedy : IsGreedySequenceUpTo P K S)
    (S_opt : Finset α) (h_opt : IsOptimal P K S_opt)
    (k : ℕ) (hk : k < K) :
    P.U S_opt - P.U (S (k + 1)) ≤ (1 - 1 / (K : ℝ)) * (P.U S_opt - P.U (S k)) := by
  -- By `submodular_upper_bound`, � $�U(S_{opt}) \le U(S_k) + \sum_{x \in S_{opt} \setminus S_k} (U(S_k \cup \{x\}) - U(S_k))$.
  have h_bound : P.U S_opt ≤ P.U (S k) + ∑ x ∈ S_opt \ S k, MarginalGain P.U (S k) x := by
    have := submodular_upper_bound P ( S k ) S_opt;
    refine' le_trans _ this;
    exact P.U_mono _ _ ( Finset.subset_union_right );
  -- Since $S$ is a greedy sequence, for any $x$, $U(S_k \cup \{x\}) - U(S_k) \le U(S_{k+1}) - U(S_k)$.
  have h_greedy_step : ∀ x ∈ S_opt \ S k, MarginalGain P.U (S k) x ≤ P.U (S (k + 1)) - P.U (S k) := by
    intro x hx
    obtain ⟨x_greedy, hx_greedy⟩ := h_greedy.right k hk;
    have := h_opt.1; aesop;
  -- Thus, $\sum_{x \in S_{opt} \setminus S_k} (U(S_k \cup \{x\}) - U(S_k)) \le |S_{opt} \setminus S_k| (U(S_{k+1}) - U(S_k))$.
  have h_sum_bound : ∑ x ∈ S_opt \ S k, MarginalGain P.U (S k) x ≤ (S_opt \ S k).card * (P.U (S (k + 1)) - P.U (S k)) := by
    convert Finset.sum_le_card_nsmul _ _ _ h_greedy_step;
    ext; simp +decide [ mul_comm ] ;
  -- Since $|S_{opt}| \le K$, $|S_{opt} \setminus S_k| \le K$.
  have h_card_bound : (S_opt \ S k).card ≤ K := by
    exact le_trans ( Finset.card_le_card fun x hx => by aesop ) h_opt.2.1;
  -- So $U(S_{opt}) - U(S_k) \le K (U(S_{k+1}) - U(S_k))$.
  have h_final_bound : P.U S_opt - P.U (S k) ≤ K * (P.U (S (k + 1)) - P.U (S k)) := by
    exact sub_le_iff_le_add'.mpr ( h_bound.trans ( add_le_add_left ( h_sum_bound.trans ( mul_le_mul_of_nonneg_right ( mod_cast h_card_bound ) ( sub_nonneg.mpr ( P.U_mono _ _ ( by
      have := h_greedy.2 k hk; unfold IsGreedyStep at this; aesop; ) ) ) ) ) _ ) );
  field_simp;
  nlinarith [ show ( K : ℝ ) ≥ 1 by norm_cast ]

/-
Solving the recurrence relation gives the bound on the optimality gap.
-/
lemma recurrence_solution (P : SubmodularProblem α) (K : ℕ) (hK : 0 < K)
    (S : ℕ → Finset α) (h_greedy : IsGreedySequenceUpTo P K S)
    (S_opt : Finset α) (h_opt : IsOptimal P K S_opt) :
    P.U S_opt - P.U (S K) ≤ (1 - 1 / (K : ℝ)) ^ K * P.U S_opt := by
  -- By induction on $k$, we can show that $P.U S_opt - P.U (S k) \leq (1 - 1 / (K : ℝ))^k * P.U S_opt$ for all $k \leq K$.
  have h_ind : ∀ k ≤ K, P.U S_opt - P.U (S k) ≤ (1 - 1 / (K : ℝ))^k * P.U S_opt := by
    intro k hk
    induction' k with k ih;
    · simp +decide [ h_greedy.1, P.U_empty ];
    · simpa only [ pow_succ', mul_assoc ] using le_trans ( greedy_recurrence P K hK S h_greedy S_opt h_opt k ( Nat.lt_of_succ_le hk ) ) ( mul_le_mul_of_nonneg_left ( ih ( Nat.le_of_succ_le hk ) ) ( sub_nonneg.2 ( div_le_self zero_le_one ( mod_cast hK ) ) ) );
  exact h_ind K le_rfl

/-
The greedy algorithm achieves a (1 - 1/e) approximation ratio for maximizing a monotone submodular function subject to a cardinality constraint.
-/
theorem Nemhauser_Wolsey_Fisher_Corrected (P : SubmodularProblem α) (K : ℕ) (_hK : K ≤ P.I.card) (hK_pos : 0 < K)
    (S : ℕ → Finset α) (h_greedy : IsGreedySequenceUpTo P K S)
    (S_opt : Finset α) (h_opt : IsOptimal P K S_opt) :
    P.U (S K) ≥ (1 - 1 / Real.exp 1) * P.U S_opt := by
  -- From `recurrence_solution`, we have $U(S_{opt}) - U(S_K) \le (1 - 1/K)^K U(S_{opt})$.
  have h_recurrence_solution : P.U S_opt - P.U (S K) ≤ (1 - 1 / (K : ℝ)) ^ K * P.U S_opt := by
    exact recurrence_solution P K hK_pos S h_greedy S_opt h_opt
  -- We know $(1 - 1/K)^K \le e^{-1} = 1/e$ from `Real.one_sub_div_pow_le_exp_neg` with $t=1$.
  have h_exp : (1 - 1 / (K : ℝ)) ^ K ≤ Real.exp (-1) := by
    convert Real.one_sub_div_pow_le_exp_neg _ using 2 ; aesop;
  norm_num [ Real.exp_neg ] at * ; nlinarith [ P.U_nonneg S_opt, P.U_nonneg ( S K ) ] ;