/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: b9beedeb-2d91-445a-b319-6fdfff07bfb5

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We construct an instance showing the gap between relevance-optimal and coverage-optimal sets can be Ω(K).
We define the items, relevance, category, and utility functions.
We define T as the set of items {(0, j) | j in Fin K} and S* as the set of items {(m, 0) | m in Fin K}.
We prove that T maximizes total relevance among sets of size K (`T_is_maximizer`).
We prove that the coverage utility of S* is K (`S_star_coverage_eq_K`).
We prove that the coverage utility of T is 1 (`T_coverage_eq_1`).
Finally, we prove that the ratio of their coverage utilities is K (`gap_is_K`).
-/

import Lipo.Prelude


set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
We define the items as pairs (m, j) from Fin K x Fin K.
Relevance is always 1.
Category is the first component m.
Coverage utility is the number of unique categories covered.
Total relevance is the sum of relevances.
-/
variable {K : ℕ} [NeZero K]

def Item (K : ℕ) := Fin K × Fin K

def relevance (_i : Item K) : ℕ := 1

def category (i : Item K) : Fin K := i.1

def coverage_utility (S : Finset (Item K)) : ℕ := (S.image category).card

def total_relevance (S : Finset (Item K)) : ℕ := S.sum relevance

/-
T is the set of items {(0, j) | j in Fin K} (using 0-based indexing for group 1).
-/
def T_set (K : ℕ) [NeZero K] : Finset (Item K) := (Finset.univ : Finset (Fin K)).image (fun j => (0, j))

/-
S* is the set of items {(m, 0) | m in Fin K} (using 0-based indexing for item 1).
-/
def S_star_set (K : ℕ) [NeZero K] : Finset (Item K) := (Finset.univ : Finset (Fin K)).image (fun m => (m, 0))

/-
The size of T is K.
-/
theorem T_card {K : ℕ} [NeZero K] : (T_set K).card = K := by
  unfold T_set ;
  rw [ Finset.card_image_of_injective ] <;> norm_num [ Function.Injective ];
  grind

/-
T is a valid maximizer of total relevance among sets of size K.
Since all items have relevance 1, total relevance is just the cardinality.
So for any set S of size K, total_relevance S = K.
And total_relevance T = K.
Thus total_relevance S ≤ total_relevance T.
-/
theorem T_is_maximizer {K : ℕ} [NeZero K] (S : Finset (Item K)) (hS : S.card = K) :
  total_relevance S ≤ total_relevance (T_set K) := by
    -- By definition of $total\_relevance$, we know that $total\_relevance S = S.card$ and $total\_relevance T = T.card$.
    have h_total_relevance : total_relevance S = S.card ∧ total_relevance (T_set K) = (T_set K).card := by
      unfold total_relevance;
      unfold relevance; aesop;
    rw [ h_total_relevance.1, h_total_relevance.2, hS, T_card ]

/-
We claim S* has coverage K.
S* is the set of items {(m, 0) | m in Fin K}.
The categories covered are {m | m in Fin K}, which is all of Fin K.
So the coverage utility is |Fin K| = K.
-/
theorem S_star_coverage_eq_K {K : ℕ} [NeZero K] : coverage_utility (S_star_set K) = K := by
  unfold coverage_utility S_star_set;
  convert Finset.card_fin K;
  ext m; aesop;

/-
We claim T has coverage 1.
T is the set of items {(0, j) | j in Fin K}.
The categories covered are {0}, since all items in T are from group 0.
So the coverage utility is |{0}| = 1.
-/
theorem T_coverage_eq_1 {K : ℕ} [NeZero K] : coverage_utility (T_set K) = 1 := by
  unfold coverage_utility T_set;
  rw [ Finset.image_image, Finset.card_eq_one ];
  exact ⟨ 0, Finset.eq_singleton_iff_unique_mem.mpr ⟨ Finset.mem_image.mpr ⟨ 0, Finset.mem_univ _, rfl ⟩, fun x hx => by obtain ⟨ y, hy, rfl ⟩ := Finset.mem_image.mp hx; rfl ⟩ ⟩

/-
Therefore U(S*) / U(T) = K, showing the gap is Ω(K).
That is: there exist instances where the relevance-optimal set achieves coverage utility that is a factor of K worse than the coverage-optimal set of the same size.
-/
theorem gap_is_K {K : ℕ} [NeZero K] : coverage_utility (S_star_set K) = K * coverage_utility (T_set K) := by
  rw [ S_star_coverage_eq_K, T_coverage_eq_1, mul_one ]