/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 80d2ee04-b6da-4b17-83bd-f86968414050

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We define the Gini coefficient and prove a lower bound for it when the population is partitioned into a "head" set $H$ and a "tail" set $T$ such that all elements in $H$ are greater than or equal to all elements in $T$.
Specifically, we prove that if $2|H| \le n$, then $G \ge \frac{E_H - E_T}{E_H + E_T} (1 - \frac{|H|}{n})$.
We demonstrate that the inequality does not hold in general without the assumption $|H| \le n/2$ (or $E_T = 0$), as shown by the counterexample $n=3, |H|=2$ with exposures $10, 10, 1$.
The proof relies on decomposing the sum of absolute differences and bounding the cross-terms between $H$ and $T$.
-/

import Lipo.Prelude


set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
The Gini coefficient is defined as the sum of absolute differences between all pairs of exposures, divided by 2n times the total exposure.
-/
def Gini (n : ℕ) (e : Fin n → ℝ) : ℝ :=
  (∑ i, ∑ j, |e i - e j|) / (2 * n * ∑ i, e i)

/-
The numerator of the Gini coefficient is at least twice the difference between (tail size * head sum) and (head size * tail sum).
-/
lemma gini_numerator_bound (n : ℕ) (e : Fin n → ℝ) (H T : Finset (Fin n))
    (h_partition : H ∪ T = Finset.univ)
    (h_disjoint : Disjoint H T)
    (h_head_ge_tail : ∀ i ∈ H, ∀ j ∈ T, e i ≥ e j) :
    ∑ i, ∑ j, |e i - e j| ≥ 2 * ((T.card : ℝ) * (∑ i ∈ H, e i) - (H.card : ℝ) * (∑ i ∈ T, e i)) := by
  -- We'll use the � fact� that $| �e�_i - e_j| = e_i - e_j �$� for $i \in � H�$ and $j \in T$, and $|e_i � -� e_j| = e �_j� - e_i$ for $i \in T$ and $j \in H$.
  have h_abs : ∑ i ∈ H, ∑ j ∈ T, |e i - e j| + ∑ i ∈ T, ∑ j ∈ H, |e i - e j| ≥ 2 * (T.card * (∑ i ∈ H, e i) - H.card * (∑ i ∈ T, e i)) := by
    -- By the properties of absolute values and sums, we can split the double sum into two separate sums.
    have h_split_sum : ∑ i ∈ H, ∑ j ∈ T, abs (e i - e j) + ∑ i ∈ T, ∑ j ∈ H, abs (e i - e j) = ∑ i ∈ H, ∑ j ∈ T, (e i - e j) + ∑ i ∈ T, ∑ j ∈ H, (e j - e i) := by
      exact congrArg₂ ( · + · ) ( Finset.sum_congr rfl fun i hi => Finset.sum_congr rfl fun j hj => by rw [ abs_of_nonneg ] ; linarith [ h_head_ge_tail i hi j hj ] ) ( Finset.sum_congr rfl fun i hi => Finset.sum_congr rfl fun j hj => by rw [ abs_of_nonpos ] <;> linarith [ h_head_ge_tail j hj i hi ] );
    simp_all +decide [ ← Finset.mul_sum _ _ _ ] ; linarith;
  refine le_trans h_abs ?_;
  rw [ ← h_partition, Finset.sum_union h_disjoint ];
  gcongr <;> aesop

/-
Under the assumption that the head set is small ($2h \le n$), the Gini coefficient is lower bounded by the relative exposure gap scaled by the tail share.
-/
theorem gini_lower_bound (n : ℕ) (e : Fin n → ℝ) (H T : Finset (Fin n)) (h : ℕ)
    (hn : n ≥ 2)
    (he_nonneg : ∀ i, 0 ≤ e i)
    (he_sum_pos : ∑ i, e i > 0)
    (h_partition : H ∪ T = Finset.univ)
    (h_disjoint : Disjoint H T)
    (hh : H.card = h)
    (h_head_ge_tail : ∀ i ∈ H, ∀ j ∈ T, e i ≥ e j)
    (h_EH_pos : ∑ i ∈ H, e i > 0)
    (h_small_head : 2 * h ≤ n) :
    Gini n e ≥ ((∑ i ∈ H, e i) - (∑ i ∈ T, e i)) / ((∑ i ∈ H, e i) + (∑ i ∈ T, e i)) * (1 - (h : ℝ) / n) := by
  have := gini_numerator_bound n e H T h_partition h_disjoint h_head_ge_tail;
  -- Substitute $|T| = n - h$ and $|H| = h$ into the inequality from `this`.
  have h_subst : ∑ i, ∑ j, |e i - e j| ≥ 2 * ((n - h : ℝ) * (∑ i ∈ H, e i) - (h : ℝ) * (∑ i ∈ T, e i)) := by
    have := Finset.card_union_of_disjoint h_disjoint; aesop;
  -- Substitute h_subst into the inequality and simplify.
  have h_simplified : Gini n e ≥ ((n - h : ℝ) * (∑ i ∈ H, e i) - (h : ℝ) * (∑ i ∈ T, e i)) / (n * (∑ i ∈ H, e i + ∑ i ∈ T, e i)) := by
    refine' le_trans _ ( show Gini n e ≥ ( ∑ i, ∑ j, |e i - e j| ) / ( 2 * n * ( ∑ i, e i ) ) from _ );
    · convert div_le_div_of_nonneg_right h_subst _ using 1;
      · rw [ ← Finset.sum_union h_disjoint, h_partition ] ; ring;
      · positivity;
    · exact le_of_eq ( by unfold Gini; ring );
  refine le_trans ?_ h_simplified;
  field_simp;
  exact div_le_div_of_nonneg_right ( by nlinarith only [ show ( h : ℝ ) ≤ n / 2 by rw [ le_div_iff₀ ] <;> norm_cast ; linarith, h_EH_pos, show ( ∑ i ∈ T, e i ) ≥ 0 by exact Finset.sum_nonneg fun _ _ => he_nonneg _ ] ) ( add_nonneg h_EH_pos.le <| Finset.sum_nonneg fun _ _ => he_nonneg _ )