/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 85f260ed-bed4-4309-bd7d-2341d4b360c0

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We proved the rearrangement inequality maximization problem.
Given a strictly decreasing function v and a strictly increasing function g,
the sum ∑ v(k) * g(r_{π(k)}) is maximized when the permutation π sorts the sequence r in descending order.
This was formalized as `rearrangement_maximization` using `Monovary.sum_comp_perm_mul_le_sum_mul`.
-/

import Lipo.Prelude


set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Let $v$ be a strictly decreasing sequence and $r$ a sequence of non-negative reals. Let $g$ be a strictly increasing function. The sum $\sum v(k) g(r_{\sigma(k)})$ is maximized when $\sigma$ sorts $r$ in descending order.
-/
open BigOperators

theorem rearrangement_maximization
  {n : ℕ} [NeZero n]
  (v : Fin n → ℝ) (hv : StrictAnti v)
  (g : ℝ → ℝ) (hg : StrictMonoOn g {x | 0 ≤ x})
  (r : Fin n → ℝ) (hr : ∀ i, 0 ≤ r i)
  (σ : Equiv.Perm (Fin n))
  (σ_star : Equiv.Perm (Fin n))
  (h_sorted : Antitone (r ∘ σ_star)) :
  ∑ i, v i * g (r (σ i)) ≤ ∑ i, v i * g (r (σ_star i)) := by
  -- Let's define the function $h$ as $h = g \circ r \circ \sigma^*$.
  set h : Fin n → ℝ := fun i => g (r (σ_star i));
  -- Since $h$ is Antitone, we can apply the Rearrangement Inequality to conclude that $\sum_{i} v_i g(r_{\sigma(i)}) \leq \sum_{i} v_i h(i)$.
  have h_rearrangement : ∀ (τ : Equiv.Perm (Fin n)), (∑ i, v i * h (τ i)) ≤ (∑ i, v i * h i) := by
    intro τ;
    -- By the properties of the rearrangement inequality, since $v$ is strictly decreasing and $h$ is antitone, we have $\sum_{i} v_{i} h_{\tau(i)} \leq \sum_{i} v_{i} h_{i}$ for any permutation $\tau$.
    have h_rearrangement : ∀ (τ : Equiv.Perm (Fin n)), (∑ i, v i * h (τ i)) ≤ (∑ i, v i * h i) := by
      intro τ
      have h_monovary : Monovary v h := by
        intro i j hij;
        exact hv.antitone ( le_of_not_gt fun hi => hij.not_ge <| hg.le_iff_le ( hr _ ) ( hr _ ) |>.2 <| h_sorted hi.le )
      exact Monovary.sum_mul_comp_perm_le_sum_mul h_monovary
    exact h_rearrangement τ;
  convert h_rearrangement ( σ_star.symm * σ ) using 1 ; aesop