/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: ad5ecb81-71b1-4e27-ba66-de3914ccd57e

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We define the coverage function `coverage` for a collection of subsets `C` of a finite set `G`, indexed by `I`. We then prove `coverage_submodular`, which states that the coverage function is submodular.
-/

import Lipo.Prelude


set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
The coverage function U(S) = |⋃_{i ∈ S} C(i)| is submodular.
-/
variable {G I : Type*} [DecidableEq G] [DecidableEq I]
variable (C : I → Finset G)

def coverage (S : Finset I) : ℕ := (S.biUnion C).card

theorem coverage_submodular (A B : Finset I) (x : I) (hsub : A ⊆ B) (_hx : x ∉ B) :
  coverage C (insert x A) - coverage C A ≥ coverage C (insert x B) - coverage C B := by
  unfold coverage;
  simp +decide only [Finset.biUnion_insert];
  -- Since $A \subseteq B$, we have $|C(x) \cap K(A)| \leq |C(x) \cap K(B)|$.
  have h_inter : (C x ∩ Finset.biUnion A C).card ≤ (C x ∩ Finset.biUnion B C).card := by
    exact Finset.card_mono fun y hy => by aesop;
  grind